### ISSUE TITLE
关于select/chan的分析

### ISSUE THREAD

**Issue by max-min** [changkun/go-under-the-hood#12]
## 动机

感觉golang的goroutine没有讲select/channel总是缺点什么

## 需求说明

能否抽时间分享一下？

**Comment by changkun** [comment]
请问你想问的是 缺 点什么？还是说想问它们的缺点？

**Comment by max-min** [comment]
不是缺点。是觉得没有channel相关分析感觉缺少点什么东西。

**Comment by changkun** [comment]
@max-min 这个算是分析吗：https://github.com/changkun/go-under-the-hood/blob/master/book/zh-cn/part3compile/ch11type/chan.md

**Comment by max-min** [comment]
我的错，没看仔细。多谢。
