### ISSUE TITLE
ch06sched/init: P 的状态转换图中 _Pdead 不会切换为 _Prunning

### ISSUE THREAD

**Issue by cnbailian** [changkun/go-under-the-hood#17]
## 实际描述

- 文件路径：https://github.com/changkun/go-under-the-hood/blob/master/book/zh-cn/part2runtime/ch06sched/init.md
- 原文段落：

P 的初始化，P 的状态转换图

## 问题描述

你好，在 `procresize` 中，对于收缩的 `gomaxprocs` 值，会将多出的 P 状态置为 `_Pdead`，同时释放其相关资源，但是不会释放掉 P 本身，这点在下文的 `procresize` 源码注释中也提到过。

```go
	// 从未使用的 p 释放资源
	for i := nprocs; i < old; i++ {
		p := allp[i]
		p.destroy()
		// 不能释放 p 本身，因为他可能在 m 进入系统调用时被引用
	}
```

还有一点是 `_Pdead` 状态应该只可能在 `procresize` 中转换为 `_Pidel`，没可能转为 `_Prunning` 吧

**Comment by changkun** [comment]
你好，在 startTheWorldWithSema 结束后 dead 状态的 p 仍然可能会被 m 绑定，从而进入 running 状态。这里的表述确实会对读者产生迷惑，我修改一下。

**Comment by cnbailian** [comment]
> 你好，在 startTheWorldWithSema 结束后 dead 状态的 p 仍然可能会被 m 绑定，从而进入 running 状态。这里的表述确实会对读者产生迷惑，我修改一下。

原来是这样，谢谢。请问这部分在哪章有写，我去学习一下。我刚看到初始化这部分，所以就直接认为它不会 running 了。

**Comment by changkun** [comment]
@cnbailian 确实是这样，我最初在分析这部分逻辑的时候，读过一部分文章有提到 P 的状态转换，但发现实际代码行为并不与其他文章中所描述的完全一致，所以我才制作了自己的版本。

`startTheWorldWithSema` 因为会涉及 GC（内容安排在调度器之后），所以在编排上没有提及。我个人并不建议跳过去看，一方面是该章节还没有写完，另一方面是 GC 在 1.14 涉及的改动较多（异步抢占的引入）会导致这部分内容的有效性存疑，我目前正在完善 GC 的内容。

你可以暂时这么理解：

```go
func startTheWorldWithSema(emitTraceEvent bool) int64 {
	mp := acquirem()
	(...)
	lock(&sched.lock)
	// 处理 P 的数量调整
	procs := gomaxprocs
	if newprocs != 0 {
		procs = newprocs
		newprocs = 0
	}
	p1 := procresize(procs)

	// 调度器可以开始调度了
	sched.gcwaiting = 0
	(...)
	unlock(&sched.lock)

	// 依次将 m 唤醒，并绑定到 p，开始执行
	for p1 != nil {
		p := p1
		p1 = p1.link.ptr()
		if p.m != 0 {
			mp := p.m.ptr()
			p.m = 0
			(...)
			mp.nextp.set(p)
			notewakeup(&mp.park)
		} else {
			// 运行 M 并运行 P. 下面不会创建一个新的 M
			newm(nil, p)
		}
	}

	// 记录 STW 结束时间
	startTime := nanotime()
	(...)
	if atomic.Load(&sched.npidle) != 0 && atomic.Load(&sched.nmspinning) == 0 {
		wakep()
	}

	releasem(mp)
	return startTime
}
```

这里的 `notewakeup`、`newm`、以及 `wakep` 都有可能与 P 重新进行绑定，从而调用 `acquirep`，例如对于 `notewakeup` 来说：

```go
func stopm() {
	_g_ := getg()

	(...)
	notesleep(&_g_.m.park)
	noteclear(&_g_.m.park)

	acquirep(_g_.m.nextp.ptr())
	_g_.m.nextp = 0
}
```

这里在 `stopm` 之后，M 可能出入休眠，但当 procresize 后 M 可能被唤醒，进而 acquirep，而 nextp 可能是一个 dead 状态的 P（复用），进而在 wirep 的调用中将其改为 running：

```go
//go:yeswritebarrierrec
func acquirep(_p_ *p) {
	wirep(_p_)
	(...)
}
//go:nowritebarrierrec
//go:nosplit
func wirep(_p_ *p) {
	_g_ := getg()
	(...)

	// 正式获取 p
	_g_.m.p.set(_p_)
	// 将 p 绑定到 m
	_p_.m.set(_g_.m)
	// 修改 p 的状态
	_p_.status = _Prunning
}
```

主要需要注意的一点：P 是一个 Go 堆上分配的值，procresize 结束后，如果不需要，需要被 GC 进行回收，但是这个回收时机可能会延后，进而即便是 dead 状态的 P 也仍然有可能被重新复用。

**Comment by cnbailian** [comment]
@changkun 明白了，非常感谢！！

**Comment by cnbailian** [comment]
@changkun hi，我又碰到了一个疑问：

我跟进到了 wirep 的源码：
```go

func wirep(_p_ *p) {
	_g_ := getg()

	if _g_.m.p != 0 || _g_.m.mcache != nil {
		throw("wirep: already in go")
	}
        // 在这里有判断 P 的状态必须等于 _Pidel，如果有 dead 状态的 P 进来，会 throw，是在哪里避免的呢？
	if _p_.m != 0 || _p_.status != _Pidle {
		id := int64(0)
		if _p_.m != 0 {
			id = _p_.m.ptr().id
		}
		print("wirep: p->m=", _p_.m, "(", id, ") p->status=", _p_.status, "\n")
		throw("wirep: invalid p state")
	}
	_g_.m.mcache = _p_.mcache
	_g_.m.p.set(_p_)
	_p_.m.set(_g_.m)
	_p_.status = _Prunning
}
```

**Comment by cnbailian** [comment]
> @changkun hi，我又碰到了一个疑问：
> 
> 我跟进到了 wirep 的源码：
> 
> ```go
> func wirep(_p_ *p) {
> 	_g_ := getg()
> 
> 	if _g_.m.p != 0 || _g_.m.mcache != nil {
> 		throw("wirep: already in go")
> 	}
>         // 在这里有判断 P 的状态必须等于 _Pidel，如果有 dead 状态的 P 进来，会 throw，是在哪里避免的呢？
> 	if _p_.m != 0 || _p_.status != _Pidle {
> 		id := int64(0)
> 		if _p_.m != 0 {
> 			id = _p_.m.ptr().id
> 		}
> 		print("wirep: p->m=", _p_.m, "(", id, ") p->status=", _p_.status, "\n")
> 		throw("wirep: invalid p state")
> 	}
> 	_g_.m.mcache = _p_.mcache
> 	_g_.m.p.set(_p_)
> 	_p_.m.set(_g_.m)
> 	_p_.status = _Prunning
> }
> ```

**Comment by changkun** [comment]
@cnbailian 你说的对，我选择了一个错误的例子，之前的回复的是错的，我刚才又重新考虑了一下 GC、timer，确实 P 切换为 _Pdead 之后，目前没有任何机会能被直接切换为 _Prunning，看起来确实是一个 Bug，我也不记得当时分析这部分内容的时候是怎么得出的这个结论了，这里需要修复一下。

**Comment by changkun** [comment]
已经修复，非常感谢 🙏
