### ISSUE TITLE
ch06sched/exec: m0.g0 在 mstart 之前是否已经初始化完成？

### ISSUE THREAD

**Issue by cnbailian** [changkun/go-under-the-hood#18]
## 问题描述

你好，我在学习这一章时了解到会在 `mstart` 中确定 m.g0 的栈边界，但是我在 darwin 系统中使用 gdb 进行调试时发现，第一个进入 `mstart` 中的线程（应该是 m0 吧），osStack = false，也就是说 g0 已经初始化完成了，请问是在哪里完成的这一步呢？

## 调试过程
系统：darwin
```shell
gdb b runtime.mstart
```
然后单步调试往下走，第一个进入断点的线程，osStack 是为false的，之后创建的都是 true。
后面创建的 M 是使用系统栈的这个我理解，在 `allocm` 中有根据系统判断是否使用系统栈，darwin 在判断逻辑中，但是第一个线程为啥没用系统栈呢......

**Comment by changkun** [comment]
你好，darwin 系统上的 Go 程序本质是 cgo 模式，线程是通过 pthread 创建，系统栈和线程本身都是操作系统进行管理的。

具体可以参考

- https://github.com/changkun/go-under-the-hood/blob/master/book/zh-cn/part2runtime/ch10abi/cgo.md
- https://github.com/changkun/go-under-the-hood/blob/master/book/zh-cn/part2runtime/ch10abi/syscall-darwin.md

**Comment by cnbailian** [comment]
感谢🙏！
