### ISSUE TITLE
typo: 9.8 接口一节中值接收者和指针接收者示例是否反了

### ISSUE THREAD

**Issue by tokers** [changkun/go-under-the-hood#22]
Hello!

在 9.8 一节讲到指针接收者和值接收者时，似乎将“值接收者”和“指针接收者”两个示例弄反了。
![image](https://user-images.githubusercontent.com/10428333/72678529-b069d580-3ae1-11ea-9170-caf49d473e0f.png)

**Comment by changkun** [comment]
非常感觉指出错误，已经修复
