### ISSUE TITLE
book: defer 关键词解释和详细分析部分可以进行一下统一

### ISSUE THREAD

**Issue by yangwenmai** [changkun/go-under-the-hood#30]
## 动机

defer 关键词的相关描述可以优化一下，并且尽量应该跟延迟函数的分析章节保持统一。

## 需求说明

延迟函数的分析：https://changkun.de/golang/zh-cn/part2runtime/ch09lang/defer/
defer 关键词解释：https://changkun.de/golang/zh-cn/part3compile/ch11type/defer/

**Comment by changkun** [comment]
defer 关键字的链接已经过期，保留存粹是因为链接兼容性考虑，在主页上找不到此章节的入口。
