### ISSUE TITLE
满怀热情地准备阅读

### ISSUE THREAD

**Issue by RanchoCooper** [changkun/go-under-the-hood#31]
## 动机
满怀热情地准备开始阅读，却发现每一节都标注了『不要阅读此小节，内容编排中』
 
希望能尽快看到初版成书 😄

**Comment by changkun** [comment]
虽然不是所有小节都在编排，调度器、垃圾回收、同步模式等许多内容均已初步形成。

但是本书的写作会非常缓慢，不会以任何形式动摇，预计不会在今年到达，对此造成的不便还请谅解。

**Comment by RanchoCooper** [comment]
能标注下已完成部分吗？

**Comment by changkun** [comment]
@RanchoCooper 因为内容还可能存在大量变动，进行标注会增加工作量。一般来说如果没有 TODO 开头的章节都可以进行适当的阅读。对此表示抱歉。

**Comment by changkun** [comment]
按你的困惑目前从网站左侧的目录中隐去了完全不建议阅读的章节，
如果没有看到变化可以考虑手动刷新页面来消除站点缓存带来的影响。

感谢你的关注，对造成的不便再次表示抱歉。

**Comment by RanchoCooper** [comment]
感谢！期待成书！
