### ISSUE TITLE
增加翻页功能

### ISSUE THREAD

**Issue by yangwenmai** [changkun/go-under-the-hood#36]
现在每一次翻页都必须编辑导航栏。可以看到最后的时候可以跳转上一页和下一页。

**Comment by changkun** [comment]
这个功能其实已经在 #32 支持了，只不过不对用户可见。
这个功能的主要难点在于需要对全书章节的前后编排具有全局理解，主题本身似乎无法解决这个需求。以下两个步骤完成后能够自动完成这一点：

1. https://github.com/changkun/go-under-the-hood/commit/0cda110bd2b4537ac453f12c0d2c5a640bfdad40

2. 手动维护一个全局章节关系，在 `website/make-cn.go` 中将前后小节的链接插入到具体的章节中。

当然步骤 2 还有另一种做法：

在 `website/make-cn.go` 中通过分析全局的文章权重来确定章节的前后关系，然后再插入到前后小节。

从脚本的实现来看，似乎前一种做法的工作量相对低很多。

**Comment by changkun** [comment]
经过实验，使用了方法 2 实现。

原因如下：

1. 方法 1 需要手动维护
2. 方法 2 实现没有想象中的复杂

**Comment by yangwenmai** [comment]
等 commit 看一看代码。

**Comment by changkun** [comment]
@yangwenmai https://github.com/changkun/go-under-the-hood/commit/43bc1394888fb447e3b46aa72b49e7decc5ca3fb
